### ISSUE TITLE
Migrate to Jakarta injection imports

### ISSUE THREAD

**Issue by basil** [openrewrite/rewrite-jenkins#29]
If the Jenkins core baseline is 2.401.2 LTS or later, migrate from `javax.inject` imports to `jakarta.inject` imports.

**Comment by timtebeek** [comment]
Linking these here: https://docs.openrewrite.org/recipes/java/migrate/jakarta
We likely have what you need already, or are able to add those quite easily.

**Comment by sghill** [comment]
Now that the recommended Jenkins baseline is 2.401.3, this has become part of the `org.openrewrite.jenkins.ModernizePlugin` recipe in #53.

A few initial PRs have been sent to plugins, attached to sghill-rewrite/campaigns#2.
