### ISSUE TITLE
0.16.0 was released but absent from maven central

### ISSUE THREAD

**Issue by jonesbusy** [openrewrite/rewrite-jenkins#76]
https://github.com/openrewrite/rewrite-jenkins/actions/runs/11710178514 ?

https://central.sonatype.com/artifact/org.openrewrite.recipe/rewrite-jenkins/versions

**Comment by mccartney** [comment]
Indeed, https://repo1.maven.org/maven2/org/openrewrite/recipe/rewrite-jenkins/ doesn't have it.
<img width="664" alt="image" src="https://github.com/user-attachments/assets/7da50599-2709-4b22-a25a-f75b56c72daf">

**Comment by timtebeek** [comment]
Hi! Yes we've had some problems with releasing; that seems to be sorted now so I'll do a new release tomorrow to flush out these issues. Thanks!
